=== SIPp/sipp/sipp.dtd
<!ELEMENT scenario ( CallLengthRepartition | ResponseTimeRepartition | Reference | send | recv | pause | nop | sendCmd | recvCmd | label | timewait)* >
<!ATTLIST scenario name CDATA #IMPLIED >

<!-- BEGIN message commands -->

<!ENTITY % messageCmdCommon '
  start_rtd NMTOKEN #IMPLIED
  rtd NMTOKEN #IMPLIED
  repeat_rtd (true|false) #IMPLIED
  crlf (true|false) #IMPLIED
  next NMTOKEN #IMPLIED
  test NMTOKEN #IMPLIED
  chance NMTOKEN #IMPLIED
  condexec NMTOKEN #IMPLIED
  condexec_inverse NMTOKEN #IMPLIED
  counter NMTOKEN #IMPLIED
  '>

<!ELEMENT send (#PCDATA|action)* >
<!ATTLIST send %messageCmdCommon; >
<!ATTLIST send retrans NMTOKEN #IMPLIED >
<!ATTLIST send lost NMTOKEN #IMPLIED >
<!ATTLIST send start_txn NMTOKEN #IMPLIED >
<!ATTLIST send ack_txn NMTOKEN #IMPLIED >

<!ELEMENT recv ( action? ) >
<!ATTLIST recv %messageCmdCommon; >
<!ATTLIST recv response CDATA #IMPLIED >
<!ATTLIST recv request CDATA #IMPLIED >
<!ATTLIST recv optional (true|false) #IMPLIED >
<!ATTLIST recv ignosesdp (true|false) #IMPLIED >
<!ATTLIST recv rrs (true|false) #IMPLIED >
<!ATTLIST recv auth (true|false) #IMPLIED >
<!ATTLIST recv lost NMTOKEN #IMPLIED >
<!ATTLIST recv timeout NMTOKEN #IMPLIED >
<!ATTLIST recv ontimeout NMTOKEN #IMPLIED >
<!ATTLIST recv regexp_match (true|false) #IMPLIED >
<!ATTLIST recv response_txn NMTOKEN #IMPLIED >

<!ELEMENT pause EMPTY >
<!ATTLIST pause %messageCmdCommon; >
<!ATTLIST pause milliseconds NMTOKEN #IMPLIED >
<!ATTLIST pause variable NMTOKEN #IMPLIED >
<!ATTLIST pause distribution NMTOKEN #IMPLIED >
<!ATTLIST pause sanity_check (true|false) #IMPLIED >

<!ELEMENT nop ( action? ) >
<!ATTLIST nop %messageCmdCommon; >
<!ATTLIST nop display CDATA #IMPLIED >

<!ELEMENT sendCmd ( #PCDATA ) >
<!ATTLIST sendCmd %messageCmdCommon; >
<!ATTLIST sendCmd dest NMTOKEN #IMPLIED >

<!ELEMENT recvCmd ( action? ) >
<!ATTLIST recvCmd %messageCmdCommon; >
<!ATTLIST recvCmd src NMTOKEN #IMPLIED >

<!-- END message commands -->

<!ELEMENT label ( #PCDATA ) >
<!ATTLIST label id NMTOKEN #IMPLIED >

<!ELEMENT ResponseTimeRepartition EMPTY >
<!ATTLIST ResponseTimeRepartition value CDATA #REQUIRED >

<!ELEMENT CallLengthRepartition EMPTY >
<!ATTLIST CallLengthRepartition value CDATA #REQUIRED >

<!ELEMENT action ( add | assign | assignstr | closecon | divide | ereg | error | exec | gettimeofday | index | insert | jump | log | lookup | multiply | pauserestore | replace | rtp_echo | sample | setdest | strcmp | subtract | test | todouble | trim | urldecode | urlencode | verifyauth | warning )+ >

<!-- BEGIN actions -->

<!-- the right-hand side of an arithmetic action: one of value or variable -->
<!ENTITY % rhs '
  value CDATA #IMPLIED
  variable CDATA #IMPLIED
  '>

<!-- string and numeric comparisons: assign_to may be left out when
     check_it or check_it_inverse is set; one of value or variable2 -->
<!ENTITY % comparison '
  assign_to CDATA #IMPLIED
  variable CDATA #REQUIRED
  value CDATA #IMPLIED
  variable2 CDATA #IMPLIED
  check_it (true|false) #IMPLIED
  check_it_inverse (true|false) #IMPLIED
  '>

<!ELEMENT ereg EMPTY >
<!ATTLIST ereg assign_to CDATA #REQUIRED >
<!ATTLIST ereg check_it (true|false) "false" >
<!ATTLIST ereg check_it_inverse (true|false) #IMPLIED >
<!ATTLIST ereg case_indep (true|false) #IMPLIED >
<!ATTLIST ereg header CDATA #IMPLIED >
<!ATTLIST ereg occurrence CDATA #IMPLIED >
<!-- old misspelling of occurrence -->
<!ATTLIST ereg occurence CDATA #IMPLIED >
<!ATTLIST ereg regexp CDATA #REQUIRED >
<!ATTLIST ereg search_in (msg|body|hdr|var) "msg" >
<!ATTLIST ereg start_line (true|false) #IMPLIED >
<!-- the variable to search when search_in="var" -->
<!ATTLIST ereg variable CDATA #IMPLIED >

<!ELEMENT log EMPTY >
<!ATTLIST log message CDATA #REQUIRED >

<!ELEMENT warning EMPTY >
<!ATTLIST warning message CDATA #REQUIRED >

<!ELEMENT error EMPTY >
<!ATTLIST error message CDATA #REQUIRED >

<!ELEMENT exec EMPTY >
<!-- exactly one of these must be present -->
<!ATTLIST exec command CDATA #IMPLIED >
<!ATTLIST exec int_cmd (stop_now|stop_gracefully|stop_call) "stop_call" >
<!ATTLIST exec play_pcap_audio CDATA #IMPLIED >
<!ATTLIST exec play_pcap_image CDATA #IMPLIED >
<!ATTLIST exec play_pcap_video CDATA #IMPLIED >
<!ATTLIST exec play_dtmf CDATA #IMPLIED >
<!ATTLIST exec rtp_stream CDATA #IMPLIED >
<!ATTLIST exec rtp_echo CDATA #IMPLIED >

<!ELEMENT rtp_echo EMPTY >
<!ATTLIST rtp_echo %rhs; >

<!ELEMENT strcmp EMPTY >
<!ATTLIST strcmp %comparison; >

<!ELEMENT test EMPTY >
<!ATTLIST test %comparison; >
<!ATTLIST test compare (equal|not_equal|greater_than|less_than|greater_than_equal|less_than_equal) #REQUIRED >

<!ELEMENT assign EMPTY >
<!ATTLIST assign assign_to CDATA #REQUIRED %rhs; >

<!ELEMENT add EMPTY >
<!ATTLIST add assign_to CDATA #REQUIRED %rhs; >

<!ELEMENT subtract EMPTY >
<!ATTLIST subtract assign_to CDATA #REQUIRED %rhs; >

<!ELEMENT multiply EMPTY >
<!ATTLIST multiply assign_to CDATA #REQUIRED %rhs; >

<!ELEMENT divide EMPTY >
<!ATTLIST divide assign_to CDATA #REQUIRED %rhs; >

<!ELEMENT jump EMPTY >
<!ATTLIST jump %rhs; >

<!ELEMENT pauserestore EMPTY >
<!ATTLIST pauserestore %rhs; >

<!ELEMENT assignstr EMPTY >
<!ATTLIST assignstr assign_to CDATA #REQUIRED >
<!ATTLIST assignstr value CDATA #REQUIRED >

<!ELEMENT todouble EMPTY >
<!ATTLIST todouble assign_to CDATA #REQUIRED >
<!ATTLIST todouble variable CDATA #REQUIRED >

<!ELEMENT sample EMPTY >
<!ATTLIST sample assign_to CDATA #REQUIRED >
<!ATTLIST sample distribution (fixed|uniform|normal|lognormal|exponential|weibull|pareto|gpareto|gamma|negbin) #REQUIRED >
<!-- the parameters of the chosen distribution -->
<!ATTLIST sample value CDATA #IMPLIED >
<!ATTLIST sample min CDATA #IMPLIED >
<!ATTLIST sample max CDATA #IMPLIED >
<!ATTLIST sample mean CDATA #IMPLIED >
<!ATTLIST sample stdev CDATA #IMPLIED >
<!ATTLIST sample lambda CDATA #IMPLIED >
<!ATTLIST sample k CDATA #IMPLIED >
<!ATTLIST sample x_m CDATA #IMPLIED >
<!ATTLIST sample shape CDATA #IMPLIED >
<!ATTLIST sample scale CDATA #IMPLIED >
<!ATTLIST sample location CDATA #IMPLIED >
<!ATTLIST sample theta CDATA #IMPLIED >
<!ATTLIST sample n CDATA #IMPLIED >
<!ATTLIST sample p CDATA #IMPLIED >

<!ELEMENT gettimeofday EMPTY >
<!-- two comma-separated variables: seconds,microseconds -->
<!ATTLIST gettimeofday assign_to CDATA #REQUIRED >

<!ELEMENT index EMPTY >
<!ATTLIST index assign_to CDATA #REQUIRED >

<!ELEMENT trim EMPTY >
<!ATTLIST trim assign_to CDATA #REQUIRED >

<!ELEMENT urldecode EMPTY >
<!ATTLIST urldecode variable CDATA #REQUIRED >

<!ELEMENT urlencode EMPTY >
<!ATTLIST urlencode variable CDATA #REQUIRED >

<!ELEMENT verifyauth EMPTY >
<!ATTLIST verifyauth assign_to CDATA #REQUIRED >
<!ATTLIST verifyauth username CDATA #REQUIRED >
<!ATTLIST verifyauth password CDATA #REQUIRED >

<!ELEMENT lookup EMPTY >
<!ATTLIST lookup assign_to CDATA #REQUIRED >
<!ATTLIST lookup file CDATA #REQUIRED >
<!ATTLIST lookup key CDATA #REQUIRED >

<!ELEMENT insert EMPTY >
<!ATTLIST insert file CDATA #REQUIRED >
<!ATTLIST insert value CDATA #REQUIRED >

<!ELEMENT replace EMPTY >
<!ATTLIST replace file CDATA #REQUIRED >
<!ATTLIST replace line CDATA #REQUIRED >
<!ATTLIST replace value CDATA #REQUIRED >

<!ELEMENT setdest EMPTY >
<!ATTLIST setdest host CDATA #REQUIRED >
<!ATTLIST setdest port CDATA #REQUIRED >
<!ATTLIST setdest protocol CDATA #REQUIRED >

<!ELEMENT closecon EMPTY >

<!-- END actions -->

<!ELEMENT timewait EMPTY >
<!ATTLIST timewait milliseconds CDATA #REQUIRED >

<!ELEMENT Reference EMPTY >
<!ATTLIST Reference variables CDATA #REQUIRED >

=== SIPp/sipp/regress/github-#0196/uas.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE scenario SYSTEM "sipp.dtd">
<scenario name="iinv-o200-obye.xml -- wjd 2014">

  <recv request="INVITE" rrs="true"/>

  <send>
    <![CDATA[

      SIP/2.0 180 Ringing
      [last_Via:]
      [last_Record-Route:]
      [last_From:]
      [last_To:];tag=[pid]SIPpTag01[call_number]
      [last_Call-ID:]
      [last_CSeq:]
      Contact: sip:[service]@[local_ip]:[local_port]
      Content-Length: 0

    ]]>
  </send>

  <send retrans="500">
    <![CDATA[

      SIP/2.0 200 OK
      [last_Via:]
      [last_Record-Route:]
      [last_From:]
      [last_To:];tag=[pid]SIPpTag01[call_number]
      [last_Call-ID:]
      [last_CSeq:]
      Contact: sip:[service]@[local_ip]:[local_port]
      Content-Type: application/sdp
      Content-Length: [len]

      v=0
      o=user1 53655765 2353687637 IN IP[local_ip_type] [local_ip]
      s=-
      c=IN IP[media_ip_type] [media_ip]
      t=0 0
      m=audio [custom_media_port] RTP/AVP 8 0
      a=rtpmap:8 PCMA/8000
      a=rtpmap:0 PCMU/8000

    ]]>
  </send>

  <recv request="ACK" rrs="true">
    <action>
      <ereg regexp=": *(.*)" search_in="hdr" header="To" assign_to="_,us"/><!-- with tag -->
      <ereg regexp=": *(.*)" search_in="hdr" header="From" assign_to="_,them"/>
    </action>
  </recv>
  <Reference variables="_"/>

  <!-- Wait for the other side to send some RTP -->
  <pause milliseconds="1000"/>

  <send start_txn="bye" retrans="500">
    <![CDATA[

      BYE [next_url] SIP/2.0
      Via: SIP/2.0/[transport] [local_ip]:[local_port];branch=[branch]
      [routes]
      From: [$us]
      To: [$them]
      [last_Call-ID:]
      CSeq: [cseq] BYE
      Contact: sip:[service]@[local_ip]:[local_port]
      Content-Length: 0

    ]]>
  </send>

  <recv response="200" response_txn="bye"/>

</scenario><!-- vim: set ts=8 sw=2 sts=2 et ai: -->

=== SIPp/sipp/regress/github-#1050/uas.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE scenario SYSTEM "sipp.dtd">

<!-- Answers AES_CM_128_HMAC_SHA1_80, and echoes the SRTP. -->
<scenario name="answer SRTP">
  <recv request="INVITE" />

  <send retrans="500">
    <![CDATA[

      SIP/2.0 200 OK
      [last_Via:]
      [last_From:]
      [last_To:];tag=[call_number]
      [last_Call-ID:]
      [last_CSeq:]
      Contact: <sip:uas@[local_ip]:[local_port]>
      Content-Type: application/sdp
      Content-Length: [len]

      v=0
      o=uas 0 0 IN IP[media_ip_type] [media_ip]
      s=-
      c=IN IP[media_ip_type] [media_ip]
      t=0 0
      m=audio [rtpstream_audio_port] RTP/SAVP 0
      a=crypto:[cryptotag1audio] [cryptosuiteaescm128sha1801audio] inline:[cryptokeyparams1audio]
      a=rtpmap:0 PCMU/8000

    ]]>
  </send>

  <recv request="ACK" />

  <nop>
    <action>
      <exec rtp_echo="startaudio,0,PCMU/8000" />
    </action>
  </nop>

  <recv request="BYE" />

  <send>
    <![CDATA[

      SIP/2.0 200 OK
      [last_Via:]
      [last_From:]
      [last_To:]
      [last_Call-ID:]
      [last_CSeq:]
      Content-Length: 0

    ]]>
  </send>

  <nop>
    <action>
      <exec rtp_echo="stopaudio,0,PCMU/8000" />
    </action>
  </nop>
</scenario>

=== SIPp/sipp/sipp_scenarios/pfca_uas_both_crypto_simple_aescm128sha132.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE scenario SYSTEM "sipp.dtd">

<scenario name="Basic MCD UAS">
  <recv request="INVITE" crlf="true">
    <action>
      <!-- Save the INVITE's CSeq header for later reuse -->
      <ereg regexp=".*" search_in="hdr" header="CSeq:" check_it="true" assign_to="1" />
      <!-- Save the INVITE's Via header for later reuse -->
      <ereg regexp=".*" search_in="hdr" header="Via:" check_it="true" assign_to="2" />
    </action>
  </recv>

  <!-- NOTE:  The INVITE's Via/CSeq headers are used explicitly here -->
  <send>
    <![CDATA[

      SIP/2.0 180 Ringing
      [last_Via:]
      [last_From:]
      [last_To:];tag=[call_number]
      [last_Call-ID:]
      [last_CSeq:]
      Require: 100rel
      RSeq: 1
      Server: VIRTUAL Mitel-3300-ICP 12.0.1.99
      Contact: <sip:[local_ip]:[local_port];transport=[transport]>
      Content-Length: 0

    ]]>
  </send>

  <recv request="PRACK">
  </recv>

  <send>
    <![CDATA[

      SIP/2.0 200 OK
      [last_Via:]
      [last_From:]
      [last_To:]
      [last_Call-ID:]
      [last_CSeq:]
      Contact: <sip:[local_ip]:[local_port];transport=[transport]>
      Server: VIRTUAL Mitel-3300-ICP-12.0.1.99
      Content-Length: 0

    ]]>
  </send>

  <!-- NOTE:  The INVITE's Via/CSeq headers are used explicitly here -->
  <send retrans="500">
    <![CDATA[

      SIP/2.0 200 OK
      Via: [$2]
      [last_From:]
      [last_To:]
      [last_Call-ID:]
      CSeq: [$1]
      Contact: <sip:[local_ip]:[local_port];transport=[transport]>
      Server: VIRTUAL Mitel-3300-ICP 12.0.1.99
      Content-Type: application/sdp
      Content-Length: [len]

      v=0
      o=16002 0 0 IN IP[media_ip_type] [media_ip]
      s=-
      c=IN IP[media_ip_type] [media_ip]
      t=0 0
      m=audio [rtpstream_audio_port] RTP/AVP 0 18 9 103 8 101
      a=crypto:[cryptotag1audio] [cryptosuiteaescm128sha1321audio] inline:[cryptokeyparams1audio]
      a=rtcp:[rtpstream_audio_port+1]
      a=sendrecv
      a=rtpmap:0 PCMU/8000
      a=rtpmap:18 G729/8000
      a=rtpmap:9 G722/16000
      a=fmtp:9 bitrate=64000
      a=rtpmap:103 G7221/16000
      a=fmtp:103 bitrate=32000
      a=rtpmap:8 PCMA/8000
      a=rtpmap:101 telephone-event/8000
      a=fmtp:101 0-11,16
      m=video [rtpstream_video_port] RTP/AVP 99 98 96 97
      a=crypto:[cryptotag1video] [cryptosuiteaescm128sha1321video] inline:[cryptokeyparams1video]
      b=TIAS:1536000
      b=AS:1597
      a=maxprate:192.0
      a=rtcp:[rtpstream_video_port+1]
      a=rtpmap:99 H264/90000
      a=fmtp:99 profile-level-id=64000d; max-mbps=108000; max-fs=3600; max-br=1280; packetization-mode=1
      a=rtpmap:98 H264/90000
      a=fmtp:98 profile-level-id=64000d; max-mbps=108000; max-fs=3600; max-br=1280; packetization-mode=0
      a=rtpmap:96 H264/90000
      a=fmtp:96 profile-level-id=42800d; max-mbps=108000; max-fs=3600; max-br=1280; packetization-mode=0
      a=rtpmap:97 H264/90000
      a=fmtp:97 profile-level-id=42800d; max-mbps=108000; max-fs=3600; max-br=1280; packetization-mode=1

    ]]>
  </send>

  <nop>
    <action>
        <exec rtp_echo="startaudio,0,PCMU/8000" />
        <exec rtp_echo="startvideo,99,H264/90000" />
    </action>
  </nop>

  <recv request="ACK">
  </recv>

  <recv request="BYE">
  </recv>

  <send>
    <![CDATA[
      SIP/2.0 200 OK
      [last_Via:]
      [last_From:]
      [last_To:]
      [last_Call-ID:]
      [last_CSeq:]
      Server: VIRTUAL Mitel-3300-ICP 12.0.1.99
      Content-Length: 0
    ]]>
  </send>

  <nop>
    <action>
        <exec rtp_echo="stopaudio,0,PCMU/8000" />
        <exec rtp_echo="stopvideo,99,H264/90000" />
    </action>
  </nop>



  <!-- definition of the response time repartition table (unit is ms)   -->
  <ResponseTimeRepartition value="10, 20, 30, 40, 50, 100, 150, 200"/>

  <!-- definition of the call length repartition table (unit is ms)     -->
  <CallLengthRepartition value="10, 50, 100, 500, 1000, 5000, 10000"/>

</scenario>

=== SIPp/sipp/sipp_scenarios/pfca_uac_apattern_g722.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE scenario SYSTEM "sipp.dtd">

<!-- UC360 INVITE/200/ACK/BYE/200 sample UAC scenario -->

<scenario name="Basic UC360 UAC">

  <send retrans="500">
    <![CDATA[

      INVITE sip:[service]@[remote_ip]:[remote_port] SIP/2.0
      Via: SIP/2.0/[transport] [local_ip]:[local_port];branch=[branch]
      From: 16001 <sip:16001@[remote_ip]:[remote_port]>;tag=[call_number]
      To: <sip:[service]@[remote_ip]:[remote_port]>
      Call-ID: [call_id]
      CSeq: 10 INVITE
      Contact: <sip:16001@[local_ip]:[local_port];transport=[transport]>
      Content-Type: application/sdp
      Max-Forwards: 70
      User-Agent: VIRTUAL Mitel-UC-Endpoint (Mitel UC360 Collaboration Point/2.1.0.99;  08:00:0F:74:80:E1)
      Subject: Conference
      Session-Expires: 3600;refresher=uas
      Min-SE: 90
      Supported: 100rel
      Require: 100rel
      Content-Length: [len]

      v=0
      o=16001 0 0 IN IP[media_ip_type] [media_ip]
      s=-
      c=IN IP[media_ip_type] [media_ip]
      t=0 0
      m=audio [media_port] RTP/AVP 9 0 18 103 8 101
      a=rtcp:[media_port+1]
      a=sendrecv
      a=rtpmap:9 G722/8000
      a=fmtp:9 bitrate=64000
      a=rtpmap:0 PCMU/8000
      a=rtpmap:18 G729/8000
      a=rtpmap:103 G7221/16000
      a=fmtp:103 bitrate=32000
      a=rtpmap:8 PCMA/8000
      a=rtpmap:101 telephone-event/8000
      a=fmtp:101 0-11,16

    ]]>
  </send>

  <recv response="100"
        optional="true">
  </recv>

  <recv response="180">
    <action>
      <!-- NOTE:  Save the 180 Ringing's CSeq header for later reuse -->
      <ereg regexp=".*" search_in="hdr" header="CSeq:" check_it="true" assign_to="1" />
      <!-- NOTE:  Save the 180 Ringing's RSeq header for later reuse -->
      <ereg regexp=".*" search_in="hdr" header="RSeq:" check_it="true" assign_to="2" />
    </action>
  </recv>

  <!-- Send PRACK for 180 Ringing -->
  <send retrans="500">
    <![CDATA[

      PRACK sip:[service]@[remote_ip]:[remote_port] SIP/2.0
      Via: SIP/2.0/[transport] [local_ip]:[local_port];branch=[branch]
      From: 16001 <sip:16001@[local_ip]:[local_port]>;tag=[call_number]
      To: <sip:[service]@[remote_ip]:[remote_port]>[peer_tag_param]
      Call-ID: [call_id]
      CSeq: 11 PRACK
      RAck: [$2][$1]
      Contact: <sip:16001@[local_ip]:[local_port];transport=[transport]>
      Max-Forwards: 70
      Subject: Conference
      Content-Length: 0

    ]]>
  </send>

  <!-- receive 200 OK / PRACK (180 Ringing) -->
  <recv response="200">
  </recv>

  <!-- receive 200 OK / INVITE -->
  <recv response="200">
  </recv>

  <!-- NOTE:  [branch-5] is used to specify reuse of same [branch] value that was used five messages earlier (e.g. INVITE) -->
  <send>
    <![CDATA[

      ACK sip:[service]@[remote_ip]:[remote_port] SIP/2.0
      Via: SIP/2.0/[transport] [local_ip]:[local_port];branch=[branch-5]
      From: "16001" <sip:16001@[remote_ip]:[remote_port]>;tag=[call_number]
      To: <sip:[service]@[remote_ip]:[remote_port]>[peer_tag_param]
      Call-ID: [call_id]
      CSeq: 10 ACK
      Content-Length: 0

    ]]>
  </send>

  <nop>
      <action>
          <exec rtp_stream="apattern,1,9,G722/8000" />
      </action>
  </nop>

  <pause milliseconds="2000" />

  <nop>
      <action>
          <exec rtp_stream="pauseapattern"/>
      </action>
  </nop>

  <pause milliseconds="2000"/>

  <nop>
      <action>
          <exec rtp_stream="resumeapattern"/>
      </action>
  </nop>

  <nop>
      <action>
          <exec rtp_stream="apattern,2,9,G722/8000" />
      </action>
  </nop>

  <pause milliseconds="2000"/>

  <nop>
      <action>
          <exec rtp_stream="apattern,3,9,G722/8000" />
      </action>
  </nop>

  <pause milliseconds="2000"/>

  <nop>
      <action>
          <exec rtp_stream="apattern,4,9,G722/8000" />
      </action>
  </nop>

  <pause milliseconds="2000"/>

  <nop>
      <action>
          <exec rtp_stream="apattern,5,9,G722/8000" />
      </action>
  </nop>

  <pause milliseconds="2000"/>

  <nop>
      <action>
          <exec rtp_stream="apattern,6,9,G722/8000" />
      </action>
  </nop>

  <pause milliseconds="2000"/>

  <send retrans="500">
    <![CDATA[

      BYE sip:[service]@[remote_ip]:[remote_port] SIP/2.0
      Via: SIP/2.0/[transport] [local_ip]:[local_port];branch=[branch-1]
      From: "16001" <sip:16001@[remote_ip]:[remote_port]>;tag=[call_number]
      To: <sip:[service]@[remote_ip]>[peer_tag_param]
      Call-ID: [call_id]
      CSeq: 12 BYE
      Contact: <sip:16001@[local_ip]:[local_port];transport=[transport]>
      Max-Forwards: 70
      Subject: Conference
      User-Agent: VIRTUAL Mitel-UC-Endpoint (Mitel UC360 Collaboration Point/2.1.0.99;  08:00:0F:74:80:E1)
      Content-Length: 0

    ]]>
  </send>

  <recv response="200">
  </recv>

  <!-- definition of the response time repartition table (unit is ms)   -->
  <ResponseTimeRepartition value="10, 20, 30, 40, 50, 100, 150, 200"/>

  <!-- definition of the call length repartition table (unit is ms)     -->
  <CallLengthRepartition value="10, 50, 100, 500, 1000, 5000, 10000"/>

</scenario>

=== SIPp/sipp/sipp_scenarios/pfca_uas_audio_g722.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE scenario SYSTEM "sipp.dtd">

<scenario name="Basic MCD UAS">
  <recv request="INVITE" crlf="true">
    <action>
      <!-- Save the INVITE's CSeq header for later reuse -->
      <ereg regexp=".*" search_in="hdr" header="CSeq:" check_it="true" assign_to="1" />
      <!-- Save the INVITE's Via header for later reuse -->
      <ereg regexp=".*" search_in="hdr" header="Via:" check_it="true" assign_to="2" />
    </action>
  </recv>

  <!-- NOTE:  The INVITE's Via/CSeq headers are used explicitly here -->
  <send>
    <![CDATA[

      SIP/2.0 180 Ringing
      [last_Via:]
      [last_From:]
      [last_To:];tag=[call_number]
      [last_Call-ID:]
      [last_CSeq:]
      Require: 100rel
      RSeq: 1
      Server: VIRTUAL Mitel-3300-ICP 12.0.1.99
      Contact: <sip:[local_ip]:[local_port];transport=[transport]>
      Content-Length: 0

    ]]>
  </send>

  <recv request="PRACK">
  </recv>

  <send>
    <![CDATA[

      SIP/2.0 200 OK
      [last_Via:]
      [last_From:]
      [last_To:]
      [last_Call-ID:]
      [last_CSeq:]
      Contact: <sip:[local_ip]:[local_port];transport=[transport]>
      Server: VIRTUAL Mitel-3300-ICP-12.0.1.99
      Content-Length: 0

    ]]>
  </send>

  <!-- NOTE:  The INVITE's Via/CSeq headers are used explicitly here -->
  <send retrans="500">
    <![CDATA[

      SIP/2.0 200 OK
      Via: [$2]
      [last_From:]
      [last_To:]
      [last_Call-ID:]
      CSeq: [$1]
      Contact: <sip:[local_ip]:[local_port];transport=[transport]>
      Server: VIRTUAL Mitel-3300-ICP 12.0.1.99
      Content-Type: application/sdp
      Content-Length: [len]

      v=0
      o=16002 0 0 IN IP[media_ip_type] [media_ip]
      s=-
      c=IN IP[media_ip_type] [media_ip]
      t=0 0
      m=audio [media_port] RTP/AVP 9 0 18 103 8 101
      a=rtcp:[media_port+1]
      a=sendrecv
      a=rtpmap:9 G722/8000
      a=fmtp:9 bitrate=64000
      a=rtpmap:0 PCMU/8000
      a=rtpmap:18 G729/8000
      a=rtpmap:103 G7221/16000
      a=fmtp:103 bitrate=32000
      a=rtpmap:8 PCMA/8000
      a=rtpmap:101 telephone-event/8000
      a=fmtp:101 0-11,16

    ]]>
  </send>

  <recv request="ACK">
  </recv>

  <recv request="BYE">
  </recv>

  <send>
    <![CDATA[
      SIP/2.0 200 OK
      [last_Via:]
      [last_From:]
      [last_To:]
      [last_Call-ID:]
      [last_CSeq:]
      Server: VIRTUAL Mitel-3300-ICP 12.0.1.99
      Content-Length: 0
    ]]>
  </send>

  <!-- definition of the response time repartition table (unit is ms)   -->
  <ResponseTimeRepartition value="10, 20, 30, 40, 50, 100, 150, 200"/>

  <!-- definition of the call length repartition table (unit is ms)     -->
  <CallLengthRepartition value="10, 50, 100, 500, 1000, 5000, 10000"/>

</scenario>

=== SIPp/sipp/regress/github-#0394/uac.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE scenario SYSTEM "sipp.dtd">
<scenario>
  <send>
    <![CDATA[

      OPTIONS sip:[service]@[remote_ip]:[remote_port] SIP/2.0
      Via: SIP/2.0/[transport] [local_ip]:[local_port];branch=[branch]
      From: <sip:sipp@[local_ip]:[local_port]>;tag=[call_number]
      To: <sip:[service]@[remote_ip]:[remote_port]>
      Call-ID: [call_id]
      CSeq: 1 OPTIONS
      Content-Length: 0

    ]]>
  </send>

  <nop>
    <action>
      <assignstr assign_to="p" value="1000"/>
      <assignstr assign_to="n" value="2"/>
      <assignstr assign_to="m" value="4"/>
      <add assign_to="n" value="3"/>
      <multiply assign_to="n" variable="m"/>
      <assignstr assign_to="bad" value="abc"/>
      <add assign_to="q" variable="bad"/>
      <log message="n=[$n] before=[clock_tick]"/>
    </action>
  </nop>

  <Reference variables="q"/>

  <pause variable="p"/>

  <nop>
    <action>
      <log message="after=[clock_tick]"/>
    </action>
  </nop>
</scenario>

=== SIPp/sipp/regress/github-#1100/uac.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE scenario SYSTEM "sipp.dtd">
<scenario name="rtp_stream plays that start at once">

  <send retrans="500">
    <![CDATA[

      INVITE sip:[service]@[remote_ip]:[remote_port] SIP/2.0
      Via: SIP/2.0/[transport] [local_ip]:[local_port];branch=[branch]
      From: sipp <sip:sipp@[local_ip]:[local_port]>;tag=[call_number]
      To: <sip:[service]@[remote_ip]:[remote_port]>
      Call-ID: [call_id]
      CSeq: 1 INVITE
      Contact: sip:sipp@[local_ip]:[local_port]
      Content-Type: application/sdp
      Content-Length: [len]

      v=0
      o=user1 53655765 2353687637 IN IP[local_ip_type] [local_ip]
      s=-
      c=IN IP[media_ip_type] [media_ip]
      t=0 0
      m=audio [rtpstream_audio_port] RTP/AVP 0
      a=rtpmap:0 PCMU/8000

    ]]>
  </send>

  <recv response="100" optional="true" />

  <recv response="180" optional="true" />

  <recv response="200" />

  <send>
    <![CDATA[

      ACK sip:[service]@[remote_ip]:[remote_port] SIP/2.0
      Via: SIP/2.0/[transport] [local_ip]:[local_port];branch=[branch]
      From: sipp <sip:sipp@[local_ip]:[local_port]>;tag=[call_number]
      To: <sip:[service]@[remote_ip]:[remote_port]>[peer_tag_param]
      Call-ID: [call_id]
      CSeq: 1 ACK
      Content-Length: 0

    ]]>
  </send>

  <!-- Plays of one packet, each over about a packet time after it
       starts: 8 of them take well under 8 idle wake-ups of the playback
       thread, which could each be up to 100 ms away. -->
  <label id="play" />

  <nop>
    <action>
      <gettimeofday assign_to="s1,us1" />
      <exec rtp_stream="packet.ulaw,1,0,PCMU/8000" />
      <exec rtp_stream="wait" timeout="2000" />
    </action>
  </nop>

  <nop next="play" test="more">
    <action>
      <gettimeofday assign_to="s2,us2" />
      <subtract assign_to="s2" variable="s1" />
      <multiply assign_to="s2" value="1000000" />
      <add assign_to="s2" variable="us2" />
      <subtract assign_to="s2" variable="us1" />
      <add assign_to="total" variable="s2" />
      <add assign_to="plays" value="1" />
      <test assign_to="more" variable="plays" compare="less_than" value="8" />
    </action>
  </nop>

  <nop>
    <action>
      <test variable="total" compare="less_than" value="270000" check_it="true" />
    </action>
  </nop>

  <send retrans="500">
    <![CDATA[

      BYE sip:[service]@[remote_ip]:[remote_port] SIP/2.0
      Via: SIP/2.0/[transport] [local_ip]:[local_port];branch=[branch]
      From: sipp <sip:sipp@[local_ip]:[local_port]>;tag=[call_number]
      To: <sip:[service]@[remote_ip]:[remote_port]>[peer_tag_param]
      Call-ID: [call_id]
      CSeq: 2 BYE
      Content-Length: 0

    ]]>
  </send>

  <recv response="200" crlf="true" />
</scenario>

=== SIPp/sipp/regress/github-#0631/uasl.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE scenario SYSTEM "sipp.dtd">

<scenario name="echo each call over SRTP with its own keys">
  <recv request="INVITE" />

  <send>
    <![CDATA[

      SIP/2.0 200 OK
      [last_Via:]
      [last_From:]
      [last_To:];tag=[call_number]
      [last_Call-ID:]
      [last_CSeq:]
      Contact: <sip:[local_ip]:[local_port]>
      Content-Type: application/sdp
      Content-Length: [len]

      v=0
      o=user1 53655765 2353687637 IN IP[media_ip_type] [media_ip]
      s=-
      c=IN IP[media_ip_type] [media_ip]
      t=0 0
      m=audio [rtpstream_audio_port] RTP/SAVP 0
      a=crypto:[cryptotag1audio] [cryptosuiteaescm128sha1801audio] inline:[cryptokeyparams1audio]
      a=rtpmap:0 PCMU/8000

    ]]>
  </send>

  <recv request="ACK" />

  <nop>
    <action>
      <exec rtp_echo="startaudio,0,PCMU/8000" />
    </action>
  </nop>

  <recv request="BYE" />

  <send>
    <![CDATA[

      SIP/2.0 200 OK
      [last_Via:]
      [last_From:]
      [last_To:]
      [last_Call-ID:]
      [last_CSeq:]
      Content-Length: 0

    ]]>
  </send>

  <nop>
    <action>
      <exec rtp_echo="stopaudio,0,PCMU/8000" />
    </action>
  </nop>
</scenario>
