=== SIPp/sipp/sipp.dtd
<!ELEMENT scenario ( CallLengthRepartition | ResponseTimeRepartition | Reference | send | recv | pause | nop | sendCmd | recvCmd | label | timewait)* >
<!ATTLIST scenario name CDATA #IMPLIED >

<!-- BEGIN message commands -->

<!ENTITY % messageCmdCommon '
  start_rtd NMTOKEN #IMPLIED
  rtd NMTOKEN #IMPLIED
  repeat_rtd (true|false) #IMPLIED
  crlf (true|false) #IMPLIED
  next NMTOKEN #IMPLIED
  test NMTOKEN #IMPLIED
  chance NMTOKEN #IMPLIED
  condexec NMTOKEN #IMPLIED
  condexec_inverse NMTOKEN #IMPLIED
  counter NMTOKEN #IMPLIED
  '>

<!ELEMENT send (#PCDATA|action)* >
<!ATTLIST send %messageCmdCommon; >
<!ATTLIST send retrans NMTOKEN #IMPLIED >
<!ATTLIST send lost NMTOKEN #IMPLIED >
<!ATTLIST send start_txn NMTOKEN #IMPLIED >
<!ATTLIST send ack_txn NMTOKEN #IMPLIED >

<!ELEMENT recv ( action? ) >
<!ATTLIST recv %messageCmdCommon; >
<!ATTLIST recv response CDATA #IMPLIED >
<!ATTLIST recv request CDATA #IMPLIED >
<!ATTLIST recv optional (true|false) #IMPLIED >
<!ATTLIST recv ignosesdp (true|false) #IMPLIED >
<!ATTLIST recv rrs (true|false) #IMPLIED >
<!ATTLIST recv auth (true|false) #IMPLIED >
<!ATTLIST recv lost NMTOKEN #IMPLIED >
<!ATTLIST recv timeout NMTOKEN #IMPLIED >
<!ATTLIST recv ontimeout NMTOKEN #IMPLIED >
<!ATTLIST recv regexp_match (true|false) #IMPLIED >
<!ATTLIST recv response_txn NMTOKEN #IMPLIED >

<!ELEMENT pause EMPTY >
<!ATTLIST pause %messageCmdCommon; >
<!ATTLIST pause milliseconds NMTOKEN #IMPLIED >
<!ATTLIST pause variable NMTOKEN #IMPLIED >
<!ATTLIST pause distribution NMTOKEN #IMPLIED >
<!ATTLIST pause sanity_check (true|false) #IMPLIED >

<!ELEMENT nop ( action? ) >
<!ATTLIST nop %messageCmdCommon; >
<!ATTLIST nop display CDATA #IMPLIED >

<!ELEMENT sendCmd ( #PCDATA ) >
<!ATTLIST sendCmd %messageCmdCommon; >
<!ATTLIST sendCmd dest NMTOKEN #IMPLIED >

<!ELEMENT recvCmd ( action? ) >
<!ATTLIST recvCmd %messageCmdCommon; >
<!ATTLIST recvCmd src NMTOKEN #IMPLIED >

<!-- END message commands -->

<!ELEMENT label ( #PCDATA ) >
<!ATTLIST label id NMTOKEN #IMPLIED >

<!ELEMENT ResponseTimeRepartition EMPTY >
<!ATTLIST ResponseTimeRepartition value CDATA #REQUIRED >

<!ELEMENT CallLengthRepartition EMPTY >
<!ATTLIST CallLengthRepartition value CDATA #REQUIRED >

<!ELEMENT action ( add | assign | assignstr | closecon | divide | ereg | error | exec | gettimeofday | index | insert | jump | log | lookup | multiply | pauserestore | replace | rtp_echo | sample | setdest | strcmp | subtract | test | todouble | trim | urldecode | urlencode | verifyauth | warning )+ >

<!-- BEGIN actions -->

<!-- the right-hand side of an arithmetic action: one of value or variable -->
<!ENTITY % rhs '
  value CDATA #IMPLIED
  variable CDATA #IMPLIED
  '>

<!-- string and numeric comparisons: assign_to may be left out when
     check_it or check_it_inverse is set; one of value or variable2 -->
<!ENTITY % comparison '
  assign_to CDATA #IMPLIED
  variable CDATA #REQUIRED
  value CDATA #IMPLIED
  variable2 CDATA #IMPLIED
  check_it (true|false) #IMPLIED
  check_it_inverse (true|false) #IMPLIED
  '>

<!ELEMENT ereg EMPTY >
<!ATTLIST ereg assign_to CDATA #REQUIRED >
<!ATTLIST ereg check_it (true|false) "false" >
<!ATTLIST ereg check_it_inverse (true|false) #IMPLIED >
<!ATTLIST ereg case_indep (true|false) #IMPLIED >
<!ATTLIST ereg header CDATA #IMPLIED >
<!ATTLIST ereg occurrence CDATA #IMPLIED >
<!-- old misspelling of occurrence -->
<!ATTLIST ereg occurence CDATA #IMPLIED >
<!ATTLIST ereg regexp CDATA #REQUIRED >
<!ATTLIST ereg search_in (msg|body|hdr|var) "msg" >
<!ATTLIST ereg start_line (true|false) #IMPLIED >
<!-- the variable to search when search_in="var" -->
<!ATTLIST ereg variable CDATA #IMPLIED >

<!ELEMENT log EMPTY >
<!ATTLIST log message CDATA #REQUIRED >

<!ELEMENT warning EMPTY >
<!ATTLIST warning message CDATA #REQUIRED >

<!ELEMENT error EMPTY >
<!ATTLIST error message CDATA #REQUIRED >

<!ELEMENT exec EMPTY >
<!-- exactly one of these must be present -->
<!ATTLIST exec command CDATA #IMPLIED >
<!ATTLIST exec int_cmd (stop_now|stop_gracefully|stop_call) "stop_call" >
<!ATTLIST exec play_pcap_audio CDATA #IMPLIED >
<!ATTLIST exec play_pcap_image CDATA #IMPLIED >
<!ATTLIST exec play_pcap_video CDATA #IMPLIED >
<!ATTLIST exec play_dtmf CDATA #IMPLIED >
<!ATTLIST exec rtp_stream CDATA #IMPLIED >
<!ATTLIST exec rtp_echo CDATA #IMPLIED >

<!ELEMENT rtp_echo EMPTY >
<!ATTLIST rtp_echo %rhs; >

<!ELEMENT strcmp EMPTY >
<!ATTLIST strcmp %comparison; >

<!ELEMENT test EMPTY >
<!ATTLIST test %comparison; >
<!ATTLIST test compare (equal|not_equal|greater_than|less_than|greater_than_equal|less_than_equal) #REQUIRED >

<!ELEMENT assign EMPTY >
<!ATTLIST assign assign_to CDATA #REQUIRED %rhs; >

<!ELEMENT add EMPTY >
<!ATTLIST add assign_to CDATA #REQUIRED %rhs; >

<!ELEMENT subtract EMPTY >
<!ATTLIST subtract assign_to CDATA #REQUIRED %rhs; >

<!ELEMENT multiply EMPTY >
<!ATTLIST multiply assign_to CDATA #REQUIRED %rhs; >

<!ELEMENT divide EMPTY >
<!ATTLIST divide assign_to CDATA #REQUIRED %rhs; >

<!ELEMENT jump EMPTY >
<!ATTLIST jump %rhs; >

<!ELEMENT pauserestore EMPTY >
<!ATTLIST pauserestore %rhs; >

<!ELEMENT assignstr EMPTY >
<!ATTLIST assignstr assign_to CDATA #REQUIRED >
<!ATTLIST assignstr value CDATA #REQUIRED >

<!ELEMENT todouble EMPTY >
<!ATTLIST todouble assign_to CDATA #REQUIRED >
<!ATTLIST todouble variable CDATA #REQUIRED >

<!ELEMENT sample EMPTY >
<!ATTLIST sample assign_to CDATA #REQUIRED >
<!ATTLIST sample distribution (fixed|uniform|normal|lognormal|exponential|weibull|pareto|gpareto|gamma|negbin) #REQUIRED >
<!-- the parameters of the chosen distribution -->
<!ATTLIST sample value CDATA #IMPLIED >
<!ATTLIST sample min CDATA #IMPLIED >
<!ATTLIST sample max CDATA #IMPLIED >
<!ATTLIST sample mean CDATA #IMPLIED >
<!ATTLIST sample stdev CDATA #IMPLIED >
<!ATTLIST sample lambda CDATA #IMPLIED >
<!ATTLIST sample k CDATA #IMPLIED >
<!ATTLIST sample x_m CDATA #IMPLIED >
<!ATTLIST sample shape CDATA #IMPLIED >
<!ATTLIST sample scale CDATA #IMPLIED >
<!ATTLIST sample location CDATA #IMPLIED >
<!ATTLIST sample theta CDATA #IMPLIED >
<!ATTLIST sample n CDATA #IMPLIED >
<!ATTLIST sample p CDATA #IMPLIED >

<!ELEMENT gettimeofday EMPTY >
<!-- two comma-separated variables: seconds,microseconds -->
<!ATTLIST gettimeofday assign_to CDATA #REQUIRED >

<!ELEMENT index EMPTY >
<!ATTLIST index assign_to CDATA #REQUIRED >

<!ELEMENT trim EMPTY >
<!ATTLIST trim assign_to CDATA #REQUIRED >

<!ELEMENT urldecode EMPTY >
<!ATTLIST urldecode variable CDATA #REQUIRED >

<!ELEMENT urlencode EMPTY >
<!ATTLIST urlencode variable CDATA #REQUIRED >

<!ELEMENT verifyauth EMPTY >
<!ATTLIST verifyauth assign_to CDATA #REQUIRED >
<!ATTLIST verifyauth username CDATA #REQUIRED >
<!ATTLIST verifyauth password CDATA #REQUIRED >

<!ELEMENT lookup EMPTY >
<!ATTLIST lookup assign_to CDATA #REQUIRED >
<!ATTLIST lookup file CDATA #REQUIRED >
<!ATTLIST lookup key CDATA #REQUIRED >

<!ELEMENT insert EMPTY >
<!ATTLIST insert file CDATA #REQUIRED >
<!ATTLIST insert value CDATA #REQUIRED >

<!ELEMENT replace EMPTY >
<!ATTLIST replace file CDATA #REQUIRED >
<!ATTLIST replace line CDATA #REQUIRED >
<!ATTLIST replace value CDATA #REQUIRED >

<!ELEMENT setdest EMPTY >
<!ATTLIST setdest host CDATA #REQUIRED >
<!ATTLIST setdest port CDATA #REQUIRED >
<!ATTLIST setdest protocol CDATA #REQUIRED >

<!ELEMENT closecon EMPTY >

<!-- END actions -->

<!ELEMENT timewait EMPTY >
<!ATTLIST timewait milliseconds CDATA #REQUIRED >

<!ELEMENT Reference EMPTY >
<!ATTLIST Reference variables CDATA #REQUIRED >

=== SIPp/sipp/regress/github-#1073/uas-first-silent.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE scenario SYSTEM "sipp.dtd">

<scenario name="echo the audio of each call but the first">
  <recv request="INVITE" />

  <send>
    <![CDATA[

      SIP/2.0 200 OK
      [last_Via:]
      [last_From:]
      [last_To:];tag=[call_number]
      [last_Call-ID:]
      [last_CSeq:]
      Contact: <sip:[local_ip]:[local_port]>
      Content-Type: application/sdp
      Content-Length: [len]

      v=0
      o=user1 53655765 2353687637 IN IP[media_ip_type] [media_ip]
      s=-
      c=IN IP[media_ip_type] [media_ip]
      t=0 0
      m=audio [rtpstream_audio_port] RTP/AVP 0
      a=rtpmap:0 PCMU/8000

    ]]>
  </send>

  <recv request="ACK">
    <action>
      <assignstr assign_to="number" value="[call_number]" />
      <todouble assign_to="n" variable="number" />
      <test assign_to="echo" variable="n" compare="greater_than" value="1" />
    </action>
  </recv>

  <nop condexec="echo">
    <action>
      <exec rtp_echo="startaudio,0,PCMU/8000" />
    </action>
  </nop>

  <recv request="BYE" />

  <send>
    <![CDATA[

      SIP/2.0 200 OK
      [last_Via:]
      [last_From:]
      [last_To:]
      [last_Call-ID:]
      [last_CSeq:]
      Content-Length: 0

    ]]>
  </send>

  <nop condexec="echo">
    <action>
      <exec rtp_echo="stopaudio,0,PCMU/8000" />
    </action>
  </nop>
</scenario>

=== SIPp/sipp/regress/github-#1006/uas.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE scenario SYSTEM "sipp.dtd">
<!-- Accepts only alice's credentials, and an Authorization header that
     starts where it should. -->
<scenario name="injected authentication uas">
  <recv request="REGISTER"/>
  <send>
    <![CDATA[
      SIP/2.0 401 Unauthorized
      [last_Via:]
      [last_From:]
      [last_To:];tag=srv
      [last_Call-ID:]
      [last_CSeq:]
      WWW-Authenticate: Digest realm="r", nonce="n0", algorithm=MD5
      Content-Length: 0
    ]]>
  </send>
  <recv request="REGISTER">
    <action>
      <ereg regexp="^Digest username=&quot;alice&quot;," search_in="hdr" header="Authorization: " check_it="true" assign_to="_"/>
      <verifyauth assign_to="authvalid" username="alice" password="secret"/>
    </action>
  </recv>
  <nop test="authvalid" next="good"/>
  <send next="end">
    <![CDATA[
      SIP/2.0 403 Forbidden
      [last_Via:]
      [last_From:]
      [last_To:];tag=srv
      [last_Call-ID:]
      [last_CSeq:]
      Content-Length: 0
    ]]>
  </send>
  <label id="good"/>
  <send>
    <![CDATA[
      SIP/2.0 200 OK
      [last_Via:]
      [last_From:]
      [last_To:];tag=srv
      [last_Call-ID:]
      [last_CSeq:]
      Content-Length: 0
    ]]>
  </send>
  <label id="end"/>
</scenario>

=== SIPp/sipp/regress/github-#1252/uas.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE scenario SYSTEM "sipp.dtd">
<!-- Challenges with an opaque of 2100 characters (from -key) and a qop
     list whose auth is past its 15th character, and accepts only
     credentials that return the opaque whole, with qop=auth. -->
<scenario name="long opaque uas">
  <recv request="REGISTER"/>
  <send>
    <![CDATA[
      SIP/2.0 401 Unauthorized
      [last_Via:]
      [last_From:]
      [last_To:];tag=srv
      [last_Call-ID:]
      [last_CSeq:]
      WWW-Authenticate: Digest realm="r", nonce="n0", qop="token-one,token-two,auth", algorithm=MD5, opaque="[opaque]"
      Content-Length: 0
    ]]>
  </send>
  <recv request="REGISTER">
    <action>
      <ereg regexp=",opaque=&quot;(o{100}){21}&quot;" search_in="msg" check_it="true" assign_to="_"/>
      <ereg regexp=",qop=auth," search_in="msg" check_it="true" assign_to="_"/>
      <verifyauth assign_to="authvalid" username="alice" password="secret"/>
    </action>
  </recv>
  <nop test="authvalid" next="good"/>
  <send next="end">
    <![CDATA[
      SIP/2.0 403 Forbidden
      [last_Via:]
      [last_From:]
      [last_To:];tag=srv
      [last_Call-ID:]
      [last_CSeq:]
      Content-Length: 0
    ]]>
  </send>
  <label id="good"/>
  <send>
    <![CDATA[
      SIP/2.0 200 OK
      [last_Via:]
      [last_From:]
      [last_To:];tag=srv
      [last_Call-ID:]
      [last_CSeq:]
      Content-Length: 0
    ]]>
  </send>
  <label id="end"/>
</scenario>

=== SIPp/sipp/regress/github-#0931/uac.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE scenario SYSTEM "sipp.dtd">
<!-- Eight actions on a three message scenario: more lines on the
     variables screen than the messages and six it pads to. -->
<scenario name="many actions">
  <send>
    <![CDATA[
      OPTIONS sip:[service]@[remote_ip]:[remote_port] SIP/2.0
      Via: SIP/2.0/[transport] [local_ip]:[local_port];branch=[branch]
      From: <sip:sipp@[local_ip]:[local_port]>;tag=[call_number]
      To: <sip:[service]@[remote_ip]:[remote_port]>
      Call-ID: [call_id]
      CSeq: 1 OPTIONS
      X-V: [$v0][$v0][$v1][$v1][$v2][$v2][$v3][$v3][$v4][$v4][$v5][$v5][$v6][$v6][$v7][$v7]
      Content-Length: 0
    ]]>
  </send>
  <nop>
    <action>
      <assign assign_to="v0" value="0"/>
      <assign assign_to="v1" value="1"/>
      <assign assign_to="v2" value="2"/>
      <assign assign_to="v3" value="3"/>
      <assign assign_to="v4" value="4"/>
      <assign assign_to="v5" value="5"/>
      <assign assign_to="v6" value="6"/>
      <assign assign_to="v7" value="7"/>
    </action>
  </nop>
  <pause milliseconds="2000"/>
</scenario>

=== SIPp/sipp/regress/github-#0501/uas.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE scenario SYSTEM "sipp.dtd">
<!-- The 200 goes out twice: with the same To-tag as a retransmission
     (-key tag2 01), or with another one as through a forking proxy
     (-key tag2 02). -->
<scenario name="200 sent twice">
  <recv request="INVITE"/>
  <send>
    <![CDATA[
      SIP/2.0 200 OK
      [last_Via:]
      [last_From:]
      [last_To:];tag=[pid]SIPpTag01[call_number]
      [last_Call-ID:]
      [last_CSeq:]
      Contact: <sip:[local_ip]:[local_port];transport=[transport]>
      Content-Length: 0
    ]]>
  </send>
  <pause milliseconds="300"/>
  <send>
    <![CDATA[
      SIP/2.0 200 OK
      [last_Via:]
      [last_From:]
      [last_To:];tag=[pid]SIPpTag[tag2][call_number]
      [last_Call-ID:]
      [last_CSeq:]
      Contact: <sip:[local_ip]:[local_port];transport=[transport]>
      Content-Length: 0
    ]]>
  </send>
  <recv request="ACK"/>
  <recv request="BYE"/>
  <send>
    <![CDATA[
      SIP/2.0 200 OK
      [last_Via:]
      [last_From:]
      [last_To:]
      [last_Call-ID:]
      [last_CSeq:]
      Content-Length: 0
    ]]>
  </send>
</scenario>

=== SIPp/sipp/regress/github-#0196/uac.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE scenario SYSTEM "sipp.dtd">
<scenario name="oinv-i200-ibye.xml -- wjd 2014">

  <send retrans="500" start_txn="invite">
    <![CDATA[

      INVITE sip:[service]@[remote_ip]:[remote_port] SIP/2.0
      Via: SIP/2.0/[transport] [local_ip]:[local_port];branch=[branch]
      From: sip:[service]@[local_ip]:[local_port];tag=[pid]SIPpTag00[call_number]
      To: sip:[service]@[remote_ip]:[remote_port]
      Call-ID: [call_id]
      CSeq: [cseq] INVITE
      Contact: sip:[service]@[local_ip]:[local_port]
      Content-Type: application/sdp
      Content-Length: [len]

      v=0
      o=user1 53655765 2353687637 IN IP[local_ip_type] [local_ip]
      s=-
      c=IN IP[media_ip_type] [media_ip]
      t=0 0
      m=audio [media_port] RTP/AVP 8 0
      a=rtpmap:8 PCMA/8000
      a=rtpmap:0 PCMU/8000

    ]]>
  </send>

  <recv response="100" optional="true" response_txn="invite"/>

  <recv response="180" optional="true" response_txn="invite"/>

  <recv response="183" optional="true" response_txn="invite"/>

  <recv response="200" rrs="true" response_txn="invite"/>

  <send ack_txn="invite">
    <![CDATA[

      ACK [next_url] SIP/2.0
      Via: SIP/2.0/[transport] [local_ip]:[local_port];branch=[branch]
      [routes]
      From: sip:[service]@[local_ip]:[local_port];tag=[pid]SIPpTag00[call_number]
      To: sip:[service]@[remote_ip]:[remote_port][peer_tag_param]
      Call-ID: [call_id]
      CSeq: [cseq] ACK
      Contact: sip:[service]@[local_ip]:[local_port]
      Content-Length: 0

    ]]>
  </send>

  <!-- Send some audio to avoid rtptimeout timers kicking in. -->
  <nop>
    <action>
      <exec rtp_stream="beep_1sec_50x160b.alaw,-1,8"/>
    </action>
  </nop>

  <recv request="BYE"/>

  <send>
    <![CDATA[

      SIP/2.0 200 OK
      [last_Via:]
      [last_Record-Route:]
      [last_From:]
      [last_To:]
      [last_Call-ID:]
      [last_CSeq:]
      Content-Length: 0

    ]]>
  </send>

  <timewait milliseconds="1000"/><!-- retransmit 200's for a while -->

</scenario>

=== SIPp/sipp/regress/github-#0914/uac.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE scenario SYSTEM "sipp.dtd">
<!-- Two failing actions, whose warnings name their variables. -->
<scenario name="action warnings">
  <nop>
    <action>
      <assign assign_to="total" value="10"/>
      <assign assign_to="count" value="0"/>
      <divide assign_to="total" variable="count"/>
      <assignstr assign_to="text" value="not a number"/>
      <todouble assign_to="number" variable="text"/>
      <log message="[$total] [$count] [$number] [$text]"/>
    </action>
  </nop>
  <send>
    <![CDATA[
      OPTIONS sip:[service]@[remote_ip]:[remote_port] SIP/2.0
      Via: SIP/2.0/[transport] [local_ip]:[local_port];branch=[branch]
      From: sipp <sip:sipp@[local_ip]:[local_port]>;tag=[call_number]
      To: <sip:[service]@[remote_ip]:[remote_port]>
      Call-ID: [call_id]
      CSeq: 1 OPTIONS
      Content-Length: 0
    ]]>
  </send>
</scenario>

=== SIPp/sipp/regress/github-#1074/uas.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE scenario SYSTEM "sipp.dtd">

<scenario name="echo the audio of each call">
  <recv request="INVITE" />

  <send>
    <![CDATA[

      SIP/2.0 200 OK
      [last_Via:]
      [last_From:]
      [last_To:];tag=[call_number]
      [last_Call-ID:]
      [last_CSeq:]
      Contact: <sip:[local_ip]:[local_port]>
      Content-Type: application/sdp
      Content-Length: [len]

      v=0
      o=user1 53655765 2353687637 IN IP[local_ip_type] [local_ip]
      s=-
      c=IN IP[media_ip_type] [media_ip]
      t=0 0
      m=audio [rtpstream_audio_port] RTP/AVP 0
      a=rtpmap:0 PCMU/8000

    ]]>
  </send>

  <recv request="ACK" />

  <nop>
    <action>
      <exec rtp_echo="startaudio,0,PCMU/8000" />
    </action>
  </nop>

  <recv request="BYE" />

  <send>
    <![CDATA[

      SIP/2.0 200 OK
      [last_Via:]
      [last_From:]
      [last_To:]
      [last_Call-ID:]
      [last_CSeq:]
      Content-Length: 0

    ]]>
  </send>

  <nop>
    <action>
      <exec rtp_echo="stopaudio,0,PCMU/8000" />
    </action>
  </nop>
</scenario>
